const countries = [
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
    "Ireland",
    "France",
    "Belgium",
    "Netherlands",
    "Luxembourg",
    "Germany",
    "Switzerland",
    "Portugal",
    "Spain",
    "Italy",
    "Malta",
    "Austria",
    "Denmark",
    "Norway",
    "Sweden",
    "Iceland",
    "Finland",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Poland",
    "Czechia",
    "Slovakia",
    "Hungary",
    "Romania",
    "Moldova",
    "Croatia",
    "Bosnia",
    "Serbia",
    "Montenegro",
    "Kosovo",
    "Albania",
    "North Macedonia",
    "Bulgaria",
    "Greece",
    "Cyprus",
    "Turkey",
    "Ukraine",
    "Georgia",
    "Azerbaijan",
    "Armenia",
    "Israel"
];

module.exports = countries;